### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by melvinwevers** [cohure/CoHuRe#5]
As we believe this community to be a bottom-up, grassroots initiative, we would like to gauge the interests and desires of the interested parties. 

Therefore, we kindly ask you if you would like to fill out the following survey: https://forms.gle/fVDUV18YseQJsuGH6

---------------------

@melvinwevers, @tedunderwood, @jorisvanzundert, @kuchbos, @michaelgavin, @rubenros1795, @jtauber, @emanjavacas, @antalvdb, @rospocher, @mikekestemont, @burtenshaw, @christofs, @informusica, @eamccarthy, @awlassche, @lrhenrickson, @JamieTehrani, @kasparvonbeelen, @mcollardanuy, @evazangerle, @Giovanni1085, @alexbrandsen, @davanstrien, @ElsLefever, @Nanne, @JoannaBy, @pvankranenburg, @faustusdotbe, @nilsreiter, @pagelj, @bleekere, @tabeatietz, @LeKonArD, @kasra-hosseini, @fkraeutli, @DavidBeavan, @versae, @peeter-t2, @jrvosse, @albertoacerbi, @HeleenWilbrink, @albertmeronyo, @BarbaraMcG, @martijnkleppe, @TScheffler, @frederik-elwert, @andreskarjus, @riddella, @hartmast

**Comment by melvinwevers** [comment]
As we believe this community to be a bottom-up, grassroots initiative, we would like to gauge the interests and desires of the interested parties.

Therefore, we kindly ask you if you would like to fill out the following survey: https://forms.gle/fVDUV18YseQJsuGH6

@t-duan, @burki, @Numapresse, @jiemakel, @vocabulista, @RebeccaKahn, @mxpiotrowski, @mromanello, @biggerpictures, @epoz, @scottbot, @sroylee, @nubuker, @e-maud, @ZoeLeBlanc, @fdlaramee, @ettorerizza, @markschwindt, @xrubio, @cneud, @jmotis, @JaimieMurdock, @colinallen, @amsichani, @dgati, @tla, @jarmoza, @essepuntato, @ManuelBurghardt, @wuebbena, @statsmaths, @lwieneke, @fedenanni, @ashleychampagne, @gmikros, @ThomasK81, @seanpue, @Giovanni1085, @kdepuydt, @proycon, @saehrle, @Cutuchiqueno, @thars3n, @pkiraly, @FranziskaDigital, @mwigham, @jdamerow, @StephanMa, @StephanMa, @maltevogl, @yngwi

**Comment by melvinwevers** [comment]
As we believe this community to be a bottom-up, grassroots initiative, we would like to gauge the interests and desires of the interested parties.

Therefore, we kindly ask you if you would like to fill out the following survey: https://forms.gle/fVDUV18YseQJsuGH6

@diegosiqueir4, @DMGoldstein, @estronks, @nrloewen, @alexhollinghead, @amcdivitt, @leoimpett, @piperandrew, @decretist, @inactinique, @fbkarsdorp

**Comment by pkiraly** [comment]
Done. How will you share the collected data?

**Comment by Cutuchiqueno** [comment]
I am not particularly eager to play the role of the devil's advocate. However, if I am not completely blind, there is absolutely nothing on the form's webiste that would at least adress loosely issues of GDPR.

In continuation of the above remark, I think it would be fair to outline what you will do with the data and how it will be handled. This is especially true, considering that Google Forms in most contexts is not considered GDPR compliant and that you even collect name and e-mail adress. Hence, it is not even an anonymous questionaire.

**Comment by melvinwevers** [comment]
@pkiraly @Cutuchiqueno The survey serves as input for a call for papers that we are currently writing. In this call, we won't report individual answers. We collected the names and addresses to make sure the respondents were not random bots. Also, we collected email addresses to be able to contact individuals to further talk about their suggestions.
